/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.shin1x1.jsonparser;

import com.github.shin1x1.jsonparser.lexer.Lexer;
import com.github.shin1x1.jsonparser.lexer.Scanner;
import com.github.shin1x1.jsonparser.parser.Parser;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class App {
    public static void main(String[] args) throws IOException {
        InputStream input;
        if (args.length > 0) {
            input = new FileInputStream(args[0]);
        } else {
            input = System.in;
        }

        try (input) {
            var scanner = new Scanner(input);
            var parser = new Parser(new Lexer(scanner));

            System.out.println(parser.parse());
        }
    }
}
