version: '3'
services:
  php-cli: &php
    image: shin1x1/php-dev:8.0-cli-buster
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/enable-docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
  php-ci:
    <<: *php
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/disable-docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
  composer:
    image: composer:2
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
