version: '3'
services:
  php-cli:
    build: docker
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/enable-docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
